version: '3.8'

services:
  db:
    image: mongo:5.0.7
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - 27017:27017
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro

